### ISSUE TITLE
Use of 6.x on Django 3 expects django-postgres-extra version that isn't released

### ISSUE THREAD

**Issue by mattmcgrattan** [SectorLabs/django-localized-fields#86]
When using 6.x with Django 3 (required because of the changes to django.utils) pip throws errors because it expects django-postgres-extra version higher than 2.0a14 but the highest version available on PyPi is lower than this.

**Comment by Photonios** [comment]
It was available on PyPi. The `a` in the version implied that it was an Alpha release. This was because you were installing a beta version of `django-localized-fields`. 6.0 is officially out now and depends on a non-alpha version of `django-postgres-extra`: https://pypi.org/project/django-localized-fields/6.0/
